import type { EventType } from '../domain/types';

/**
 * Building blocks for synthetic sample events (spec §148). Every organizer, venue, speaker
 * and exhibitor here is fictional. Generated events are flagged `isDemo` and labelled
 * "Sample event" in the app; they are never presented as verified real-world events.
 */

export type EventTemplate = {
  key: string;
  names: string[];
  eventType: EventType;
  /** Shapes speakers, exhibitors, agenda, timings and price. */
  format: 'conference' | 'expo' | 'workshop' | 'meetup' | 'webinar';
  categoryIds: string[];
  technologyIds: string[];
  industryIds: string[];
  tags: string[];
  days: [number, number];
  cities: string[];
  organizerIds: string[];
  audience: string[];
  /** One sentence; {days} and {city} are filled in. */
  summary: string;
  expect: string[];
  sessions: string[];
};

export const DEMO_ORGANIZERS: { id: string; name: string; description: string }[] = [
  { id: 'org-enterprise-pulse', name: 'Enterprise Pulse Events', description: 'Runs conferences and roundtables for enterprise application leaders across India.' },
  { id: 'org-kaveri-media', name: 'Kaveri Business Media', description: 'Organises trade exhibitions for manufacturing, engineering and industrial sectors.' },
  { id: 'org-deccan-tech', name: 'Deccan Tech Circle', description: 'A community that hosts practitioner meetups and workshops in South India.' },
  { id: 'org-indotrade', name: 'IndoTrade Fairs', description: 'Produces business-to-business trade shows in major Indian cities.' },
  { id: 'org-summit-works', name: 'Summit Works India', description: 'Hosts leadership summits for CIOs, CFOs and transformation heads.' },
  { id: 'org-open-erp', name: 'Open ERP Community India', description: 'A volunteer community for open-source ERP users and implementation partners.' },
  { id: 'org-securenext', name: 'SecureNext Forums', description: 'Runs cybersecurity summits and closed-door CISO roundtables.' },
  { id: 'org-cloudnative', name: 'CloudNative India Collective', description: 'A practitioner community for cloud, platform engineering and DevOps teams.' },
  { id: 'org-people-work', name: 'People & Work Forum', description: 'Brings HR and people-technology leaders together through conclaves and workshops.' },
  { id: 'org-scl-network', name: 'Supply Chain Leaders Network', description: 'Connects supply chain, procurement and logistics leaders through regional forums.' },
  { id: 'org-finlead', name: 'FinLead Events', description: 'Organises finance leadership forums on technology, automation and reporting.' },
  { id: 'org-applied-ai', name: 'Applied AI Society India', description: 'A professional society focused on applied artificial intelligence in industry.' },
  { id: 'org-west-mfg', name: 'Western Region Manufacturers Council', description: 'An industry body for manufacturers in western India.' },
  { id: 'org-startup-bridge', name: 'Startup Bridge India', description: 'Hosts founder meetups, demo days and investor forums.' },
];

/** Fictional venue names; the area names are real neighbourhoods. */
export const DEMO_VENUES: Record<string, { name: string; area: string }[]> = {
  delhi: [
    { name: 'Riverstone Convention Centre', area: 'Aerocity' },
    { name: 'Northgate Expo Grounds', area: 'Dwarka' },
  ],
  gurugram: [{ name: 'Meridian Conference Hall', area: 'Cyber City' }],
  noida: [
    { name: 'Cedar Expo Centre', area: 'Sector 62' },
    { name: 'Bluepeak Exhibition Park', area: 'Knowledge Park' },
  ],
  mumbai: [
    { name: 'Harbourline Exhibition Centre', area: 'Goregaon East' },
    { name: 'Crescent Business Auditorium', area: 'Bandra Kurla Complex' },
  ],
  pune: [
    { name: 'Granite Convention Hall', area: 'Hinjewadi' },
    { name: 'Emberwood Expo Grounds', area: 'Moshi' },
  ],
  bengaluru: [
    { name: 'Banyan Conference Centre', area: 'Whitefield' },
    { name: 'Orchid Expo Grounds', area: 'Hebbal' },
  ],
  hyderabad: [
    { name: 'Indigo Convention Centre', area: 'HITEC City' },
    { name: 'Silverline Exhibition Hall', area: 'Madhapur' },
  ],
  chennai: [
    { name: 'Coastline Convention Centre', area: 'Guindy' },
    { name: 'Teakwood Expo Hall', area: 'Old Mahabalipuram Road' },
  ],
  kolkata: [{ name: 'Eastbank Convention Centre', area: 'New Town' }],
  ahmedabad: [{ name: 'Sabar Conference Hall', area: 'SG Highway' }],
  gandhinagar: [{ name: 'Westwind Exhibition Grounds', area: 'Sector 17' }],
  jaipur: [{ name: 'Pinkstone Convention Centre', area: 'Sitapura' }],
  goa: [{ name: 'Seabreeze Conference Resort', area: 'Candolim' }],
  lucknow: [{ name: 'Gomti Convention Hall', area: 'Gomti Nagar' }],
  chandigarh: [{ name: 'Sector Seventeen Business Centre', area: 'Sector 17' }],
  indore: [{ name: 'Malwa Convention Centre', area: 'Vijay Nagar' }],
  kochi: [{ name: 'Backwater Conference Centre', area: 'Kakkanad' }],
  coimbatore: [{ name: 'Kovai Trade Grounds', area: 'Avinashi Road' }],
  nagpur: [{ name: 'Orangeline Convention Hall', area: 'Wardha Road' }],
  surat: [{ name: 'Tapti Exhibition Centre', area: 'Sarsana' }],
};

export const SPEAKER_FIRST = ['Aarav', 'Ananya', 'Rohan', 'Priya', 'Vikram', 'Meera', 'Kabir', 'Isha', 'Arjun', 'Neha', 'Siddharth', 'Kavya', 'Rahul', 'Divya', 'Aditya', 'Sneha', 'Karan', 'Pooja', 'Nikhil', 'Ritu', 'Varun', 'Shreya', 'Manish', 'Lakshmi', 'Imran', 'Farah', 'Gurpreet', 'Tenzin'];
export const SPEAKER_LAST = ['Mehta', 'Iyer', 'Sharma', 'Reddy', 'Nair', 'Kulkarni', 'Banerjee', 'Gupta', 'Rao', 'Menon', 'Joshi', 'Desai', 'Chatterjee', 'Pillai', 'Singh', 'Verma', 'Patel', 'Bhat', 'Khanna', 'Ahmed', 'Dutta', 'Kapoor'];
export const SPEAKER_ROLES = ['Chief Information Officer', 'Chief Technology Officer', 'Head of Digital Transformation', 'VP, Manufacturing Excellence', 'Director, Supply Chain', 'Chief Human Resources Officer', 'Chief Financial Officer', 'Principal Consultant', 'Plant Head', 'Chief Information Security Officer', 'Head of Data Science', 'ERP Programme Lead', 'Director, Procurement', 'Head of Cloud Platforms', 'Founder & CEO'];
export const DEMO_COMPANIES = ['Narmada Auto Components', 'Sahyadri Foods', 'Vindhya Cement Works', 'Tapti Textiles', 'Godavari Polymers', 'Malabar Freight Lines', 'Aravali Electronics', 'Konkan Chemicals', 'Shivalik Pharma', 'Nilgiri Engineering', 'Chambal Fertilisers & Agro', 'Satpura Steel Tubes', 'Kosi Power Systems', 'Mahanadi Logistics', 'Sutlej Motors', 'Brahmaputra Retail'];
export const EXHIBITOR_PREFIX = ['Apex', 'Vertex', 'Nimbus', 'Quantum', 'Zenith', 'Orbit', 'Pinnacle', 'Helix', 'Stratus', 'Vector', 'Cobalt', 'Nova', 'Sterling', 'Lumen', 'Tessera', 'Kestrel', 'Arcadia', 'Bluefin'];
export const EXHIBITOR_SUFFIX: Record<string, string[]> = {
  tech: ['ERP Solutions', 'Cloud Services', 'Analytics', 'Digital Labs', 'Software Systems', 'Data Systems', 'Consulting', 'Security Labs'],
  industrial: ['Automation', 'Machine Tools', 'Robotics', 'Packaging Systems', 'Industrial Controls', 'Precision Engineering', 'Materials', 'Sensors'],
};

const conferenceSessions = (topic: string) => [
  `Opening keynote: the state of ${topic} in India`,
  `Panel: lessons from large ${topic} programmes`,
  `Case study: a mid-market ${topic} rollout`,
  `Fireside chat with industry leaders`,
  `Roundtable: budgets, teams and timelines`,
  `Partner showcase and demos`,
];

export const DEMO_TEMPLATES: EventTemplate[] = [
  {
    key: 'sap-forum',
    names: ['SAP Transformation Forum', 'S/4HANA Migration Summit', 'Intelligent Enterprise Conclave'],
    eventType: 'conference',
    format: 'conference',
    categoryIds: ['erp', 'digital-transformation'],
    technologyIds: ['sap', 'erp-generic'],
    industryIds: ['manufacturing', 'it'],
    tags: ['SAP', 'ERP', 'S/4HANA', 'Enterprise'],
    days: [1, 2],
    cities: ['delhi', 'gurugram', 'mumbai', 'bengaluru', 'hyderabad', 'pune', 'chennai'],
    organizerIds: ['org-enterprise-pulse', 'org-summit-works'],
    audience: ['CIOs and IT heads', 'SAP programme managers', 'Finance and operations leaders', 'Implementation partners'],
    summary: 'A {days} conference in {city} for leaders running SAP and S/4HANA programmes, with case studies, panels and partner demos.',
    expect: ['Customer case studies on S/4HANA migrations and clean-core approaches.', 'Panels on data migration, change management and programme governance.', 'A partner area with implementation and managed-services firms.'],
    sessions: [...conferenceSessions('SAP'), 'Clean core and extensions in practice', 'Data migration without surprises'],
  },
  {
    key: 'sap-mfg',
    names: ['SAP for Manufacturing Leaders Meet', 'Digital Plant with SAP Forum'],
    eventType: 'industry_forum',
    format: 'conference',
    categoryIds: ['erp', 'manufacturing', 'industry-4'],
    technologyIds: ['sap', 'iot'],
    industryIds: ['manufacturing', 'automotive', 'chemicals'],
    tags: ['SAP', 'Manufacturing', 'MES', 'Industry 4.0'],
    days: [1, 1],
    cities: ['pune', 'chennai', 'ahmedabad', 'noida', 'hyderabad'],
    organizerIds: ['org-enterprise-pulse', 'org-west-mfg'],
    audience: ['Plant heads', 'Manufacturing IT leaders', 'Operations and quality heads'],
    summary: 'A one-day forum in {city} on connecting SAP with plant operations, quality and maintenance.',
    expect: ['Plant-floor case studies from discrete and process manufacturers.', 'Sessions on production planning, quality and maintenance in SAP.', 'Small-group discussions for manufacturing IT teams.'],
    sessions: [...conferenceSessions('SAP in manufacturing'), 'Shop-floor integration patterns'],
  },
  {
    key: 'odoo-meetup',
    names: ['Odoo Community Meetup', 'Open-Source ERP Day'],
    eventType: 'meetup',
    format: 'meetup',
    categoryIds: ['erp', 'startups'],
    technologyIds: ['odoo', 'erp-generic'],
    industryIds: ['retail', 'manufacturing', 'it'],
    tags: ['Odoo', 'ERP', 'Open Source', 'SME'],
    days: [1, 1],
    cities: ['hyderabad', 'bengaluru', 'pune', 'ahmedabad', 'goa', 'kochi', 'jaipur'],
    organizerIds: ['org-open-erp', 'org-deccan-tech'],
    audience: ['Odoo users and administrators', 'Implementation partners', 'SME owners evaluating ERP'],
    summary: 'An evening meetup in {city} for Odoo users, partners and businesses evaluating open-source ERP.',
    expect: ['Short talks from businesses running Odoo in production.', 'Open discussion on customisation, upgrades and hosting.', 'Networking with local implementation partners.'],
    sessions: ['Welcome and introductions', 'Lightning talks from Odoo users', 'Upgrades without pain', 'Open Q&A and networking'],
  },
  {
    key: 'odoo-workshop',
    names: ['Odoo for SMEs Workshop', 'Odoo Implementation Bootcamp'],
    eventType: 'workshop',
    format: 'workshop',
    categoryIds: ['erp'],
    technologyIds: ['odoo', 'erp-generic'],
    industryIds: ['retail', 'manufacturing'],
    tags: ['Odoo', 'ERP', 'Hands-on'],
    days: [1, 2],
    cities: ['goa', 'pune', 'bengaluru', 'mumbai', 'indore'],
    organizerIds: ['org-open-erp'],
    audience: ['Functional consultants', 'Finance and inventory teams', 'SME decision makers'],
    summary: 'A hands-on {days} workshop in {city} covering Odoo setup for sales, inventory and accounting.',
    expect: ['Guided exercises on a sample company database.', 'Inventory, purchase and accounting flows end to end.', 'Bring a laptop; seats are limited.'],
    sessions: ['Setting up the company', 'Sales and inventory flows', 'Purchase and vendor bills', 'Accounting and reports'],
  },
  {
    key: 'erp-summit',
    names: ['ERP Leaders Summit', 'Enterprise Applications Conclave', 'Mid-Market ERP Forum'],
    eventType: 'summit',
    format: 'conference',
    categoryIds: ['erp', 'digital-transformation', 'finance-tech'],
    technologyIds: ['erp-generic', 'sap', 'oracle', 'ms-dynamics', 'odoo'],
    industryIds: ['manufacturing', 'retail', 'it'],
    tags: ['ERP', 'Enterprise', 'Selection', 'Cloud ERP'],
    days: [1, 2],
    cities: ['mumbai', 'delhi', 'bengaluru', 'hyderabad', 'kolkata', 'chennai'],
    organizerIds: ['org-summit-works', 'org-enterprise-pulse'],
    audience: ['CIOs and CFOs', 'ERP programme owners', 'Mid-market business leaders'],
    summary: 'A {days} summit in {city} on choosing, implementing and running ERP across SAP, Oracle, Microsoft Dynamics and Odoo.',
    expect: ['Comparisons of cloud ERP options for mid-market companies.', 'Talks on selection, total cost and implementation risk.', 'Vendor-neutral panels and partner meetings.'],
    sessions: [...conferenceSessions('ERP'), 'Cloud ERP for the mid-market'],
  },
  {
    key: 'dynamics-day',
    names: ['Dynamics 365 User Day', 'Microsoft Business Applications Meet'],
    eventType: 'technology_event',
    format: 'conference',
    categoryIds: ['erp', 'crm'],
    technologyIds: ['ms-dynamics', 'azure', 'crm-generic'],
    industryIds: ['retail', 'it', 'bfsi'],
    tags: ['Dynamics 365', 'ERP', 'CRM', 'Power Platform'],
    days: [1, 1],
    cities: ['bengaluru', 'hyderabad', 'pune', 'noida'],
    organizerIds: ['org-deccan-tech', 'org-enterprise-pulse'],
    audience: ['Dynamics administrators and developers', 'Business applications teams'],
    summary: 'A one-day user event in {city} for teams running Microsoft Dynamics 365 and the Power Platform.',
    expect: ['Practitioner talks on finance, supply chain and CRM modules.', 'Sessions on integrations and reporting.', 'Community networking.'],
    sessions: conferenceSessions('Dynamics 365'),
  },
  {
    key: 'oracle-forum',
    names: ['Oracle Cloud Applications Forum', 'NetSuite Users Roundtable'],
    eventType: 'roundtable',
    format: 'conference',
    categoryIds: ['erp', 'cloud', 'finance-tech'],
    technologyIds: ['oracle', 'erp-generic'],
    industryIds: ['bfsi', 'manufacturing'],
    tags: ['Oracle', 'NetSuite', 'ERP', 'Finance'],
    days: [1, 1],
    cities: ['mumbai', 'delhi', 'bengaluru', 'chennai'],
    organizerIds: ['org-summit-works', 'org-finlead'],
    audience: ['Finance systems owners', 'Oracle application teams'],
    summary: 'A closed-door roundtable in {city} for finance and IT teams running Oracle cloud applications.',
    expect: ['Peer discussions under the Chatham House Rule.', 'Short case presentations from finance teams.'],
    sessions: ['Welcome and context', 'Case presentation', 'Roundtable discussion', 'Wrap-up'],
  },
  {
    key: 'crm-summit',
    names: ['Customer Experience & CRM Summit', 'CX Technology Forum'],
    eventType: 'summit',
    format: 'conference',
    categoryIds: ['crm', 'digital-transformation'],
    technologyIds: ['crm-generic', 'salesforce', 'zoho', 'ms-dynamics'],
    industryIds: ['retail', 'bfsi'],
    tags: ['CRM', 'Customer Experience', 'Salesforce', 'Zoho'],
    days: [1, 2],
    cities: ['mumbai', 'bengaluru', 'gurugram', 'chennai'],
    organizerIds: ['org-summit-works'],
    audience: ['CX and marketing technology leaders', 'CRM platform owners'],
    summary: 'A {days} summit in {city} on customer experience platforms, CRM programmes and service technology.',
    expect: ['Talks on CRM consolidation and data quality.', 'Panels on service automation.', 'Platform showcase.'],
    sessions: conferenceSessions('CRM'),
  },
  {
    key: 'hr-tech',
    names: ['HR Tech Conclave', 'Future of Work Summit', 'Payroll & HRMS Forum'],
    eventType: 'conference',
    format: 'conference',
    categoryIds: ['hr-tech'],
    technologyIds: ['hrms', 'genai'],
    industryIds: ['it', 'manufacturing', 'bfsi'],
    tags: ['HRMS', 'HR Tech', 'Payroll', 'Future of Work'],
    days: [1, 2],
    cities: ['bengaluru', 'gurugram', 'mumbai', 'hyderabad', 'pune'],
    organizerIds: ['org-people-work'],
    audience: ['CHROs and HR heads', 'HR operations and payroll teams', 'HRIS owners'],
    summary: 'A {days} conference in {city} on HR technology, HRMS platforms and the future of work.',
    expect: ['Case studies on HRMS consolidation and payroll automation.', 'Sessions on hiring, learning and employee experience.', 'An HR technology showcase.'],
    sessions: [...conferenceSessions('HR technology'), 'Payroll compliance automation'],
  },
  {
    key: 'mdm-forum',
    names: ['Master Data Management Forum', 'Data Governance & MDM Day'],
    eventType: 'industry_forum',
    format: 'conference',
    categoryIds: ['mdm', 'data'],
    technologyIds: ['sap', 'erp-generic'],
    industryIds: ['manufacturing', 'pharma', 'retail'],
    tags: ['MDM', 'Data Governance', 'Data Quality'],
    days: [1, 1],
    cities: ['mumbai', 'bengaluru', 'hyderabad', 'pune'],
    organizerIds: ['org-enterprise-pulse'],
    audience: ['Data governance leads', 'ERP and analytics teams'],
    summary: 'A one-day forum in {city} on master data management, data quality and governance for ERP-led companies.',
    expect: ['Material and customer master clean-up case studies.', 'Governance operating models that stick.'],
    sessions: conferenceSessions('master data management'),
  },
  {
    key: 'ai-summit',
    names: ['Applied AI Summit', 'GenAI for Enterprise Conference', 'Machine Learning Practitioners Day'],
    eventType: 'conference',
    format: 'conference',
    categoryIds: ['ai', 'data', 'digital-transformation'],
    technologyIds: ['genai', 'ml'],
    industryIds: ['it', 'bfsi', 'healthcare', 'manufacturing'],
    tags: ['AI', 'GenAI', 'Machine Learning', 'Enterprise AI'],
    days: [1, 2],
    cities: ['bengaluru', 'hyderabad', 'mumbai', 'delhi', 'pune', 'chennai', 'kochi'],
    organizerIds: ['org-applied-ai', 'org-summit-works'],
    audience: ['Data and AI leaders', 'CTOs and engineering heads', 'Product and analytics teams'],
    summary: 'A {days} conference in {city} on putting AI and generative AI into production in Indian enterprises.',
    expect: ['Production case studies across banking, healthcare and manufacturing.', 'Sessions on governance, evaluation and cost.', 'Hands-on clinics with practitioners.'],
    sessions: [...conferenceSessions('enterprise AI'), 'Evaluating GenAI systems', 'AI governance in regulated industries'],
  },
  {
    key: 'ai-mfg',
    names: ['AI in Manufacturing Forum', 'Smart Factory AI Day'],
    eventType: 'industry_forum',
    format: 'conference',
    categoryIds: ['ai', 'manufacturing', 'industry-4'],
    technologyIds: ['ml', 'iot', 'robotics'],
    industryIds: ['manufacturing', 'automotive', 'electronics'],
    tags: ['AI', 'Manufacturing', 'Predictive Maintenance', 'Computer Vision'],
    days: [1, 1],
    cities: ['pune', 'chennai', 'noida', 'ahmedabad', 'coimbatore'],
    organizerIds: ['org-applied-ai', 'org-west-mfg'],
    audience: ['Plant and operations heads', 'Industrial engineers', 'Manufacturing IT teams'],
    summary: 'A one-day forum in {city} on AI for quality inspection, maintenance and planning on the factory floor.',
    expect: ['Computer vision and predictive maintenance case studies.', 'Talks on data readiness in plants.'],
    sessions: conferenceSessions('AI in manufacturing'),
  },
  {
    key: 'mfg-expo',
    names: ['Smart Manufacturing Expo', 'Precision Engineering Expo', 'Industrial Automation Fair'],
    eventType: 'expo',
    format: 'expo',
    categoryIds: ['manufacturing', 'automation', 'industry-4'],
    technologyIds: ['robotics', 'iot'],
    industryIds: ['manufacturing', 'automotive', 'electronics'],
    tags: ['Manufacturing', 'Automation', 'Machine Tools', 'Exhibition'],
    days: [3, 4],
    cities: ['delhi', 'noida', 'pune', 'chennai', 'ahmedabad', 'gandhinagar', 'bengaluru', 'coimbatore'],
    organizerIds: ['org-kaveri-media', 'org-west-mfg', 'org-indotrade'],
    audience: ['Manufacturers and plant owners', 'Procurement and engineering teams', 'Distributors and dealers'],
    summary: 'A {days} exhibition in {city} for manufacturing, automation and engineering, with exhibitors across machine tools, robotics and controls.',
    expect: ['Exhibitors across machine tools, robotics, controls and sensors.', 'Live machine demonstrations in the halls.', 'Seminars on automation and Industry 4.0.'],
    sessions: ['Inauguration', 'Seminar: automation for MSMEs', 'Seminar: Industry 4.0 readiness', 'Buyer–seller meetings'],
  },
  {
    key: 'industry4',
    names: ['Industry 4.0 Conclave', 'Digital Manufacturing Summit'],
    eventType: 'summit',
    format: 'conference',
    categoryIds: ['industry-4', 'manufacturing', 'digital-transformation'],
    technologyIds: ['iot', 'erp-generic', 'sap'],
    industryIds: ['manufacturing', 'automotive', 'pharma'],
    tags: ['Industry 4.0', 'Manufacturing', 'IIoT', 'Digital Twin'],
    days: [1, 2],
    cities: ['pune', 'chennai', 'gurugram', 'ahmedabad', 'hyderabad'],
    organizerIds: ['org-summit-works', 'org-west-mfg'],
    audience: ['Manufacturing CXOs', 'Digital transformation heads', 'Plant IT leaders'],
    summary: 'A {days} summit in {city} on Industry 4.0 programmes, connected plants and ERP-to-shop-floor integration.',
    expect: ['Roadmaps from manufacturers at different maturity levels.', 'Panels on IIoT platforms and digital twins.'],
    sessions: conferenceSessions('Industry 4.0'),
  },
  {
    key: 'trade-packaging',
    names: ['Packaging Machinery Expo', 'Plastics & Polymers Trade Fair', 'Building Materials Expo', 'Electronics Manufacturing Show'],
    eventType: 'trade_show',
    format: 'expo',
    categoryIds: ['business', 'manufacturing'],
    technologyIds: [],
    industryIds: ['chemicals', 'construction', 'electronics', 'manufacturing'],
    tags: ['Trade Show', 'Exhibition', 'B2B'],
    days: [3, 4],
    cities: ['mumbai', 'delhi', 'noida', 'ahmedabad', 'surat', 'kolkata', 'chennai', 'bengaluru'],
    organizerIds: ['org-indotrade', 'org-kaveri-media'],
    audience: ['Manufacturers and converters', 'Buyers and distributors', 'Exporters'],
    summary: 'A {days} trade show in {city} bringing together suppliers, buyers and distributors.',
    expect: ['Exhibitors from machinery, materials and services.', 'Buyer–seller meetings and product launches.'],
    sessions: ['Inauguration', 'Product launches', 'Buyer–seller meetings', 'Industry awards'],
  },
  {
    key: 'msme-expo',
    names: ['MSME Business Expo', 'Export Opportunities Fair'],
    eventType: 'exhibition',
    format: 'expo',
    categoryIds: ['business'],
    technologyIds: [],
    industryIds: ['manufacturing', 'textiles', 'retail'],
    tags: ['MSME', 'Exhibition', 'Exports', 'B2B'],
    days: [2, 3],
    cities: ['jaipur', 'lucknow', 'indore', 'surat', 'ludhiana', 'coimbatore', 'nagpur'],
    organizerIds: ['org-indotrade'],
    audience: ['MSME owners', 'Exporters and traders', 'Service providers'],
    summary: 'A {days} business exhibition in {city} for MSMEs, exporters and their service providers.',
    expect: ['Stalls from manufacturers, banks and service providers.', 'Talks on exports, credit and digital tools for MSMEs.'],
    sessions: ['Inauguration', 'Session: exports for small businesses', 'Session: digital tools for MSMEs', 'Networking'],
  },
  {
    key: 'cloud-summit',
    names: ['Cloud Native Summit', 'Hybrid Cloud Forum'],
    eventType: 'conference',
    format: 'conference',
    categoryIds: ['cloud', 'devops'],
    technologyIds: ['aws', 'azure', 'gcp', 'kubernetes'],
    industryIds: ['it', 'bfsi'],
    tags: ['Cloud', 'Kubernetes', 'DevOps', 'Platform Engineering'],
    days: [1, 2],
    cities: ['bengaluru', 'hyderabad', 'pune', 'chennai', 'noida', 'mumbai'],
    organizerIds: ['org-cloudnative'],
    audience: ['Platform and cloud engineers', 'Engineering managers', 'SRE teams'],
    summary: 'A {days} conference in {city} on cloud platforms, Kubernetes and platform engineering.',
    expect: ['Talks from teams running large platforms in production.', 'Sessions on cost, reliability and security.', 'Workshops for hands-on learning.'],
    sessions: [...conferenceSessions('cloud platforms'), 'FinOps in practice'],
  },
  {
    key: 'devops-day',
    names: ['DevOps & Platform Engineering Day', 'SRE Community Meetup'],
    eventType: 'meetup',
    format: 'meetup',
    categoryIds: ['devops', 'cloud'],
    technologyIds: ['kubernetes', 'aws'],
    industryIds: ['it'],
    tags: ['DevOps', 'SRE', 'Kubernetes'],
    days: [1, 1],
    cities: ['bengaluru', 'hyderabad', 'pune', 'chennai', 'kochi'],
    organizerIds: ['org-cloudnative', 'org-deccan-tech'],
    audience: ['DevOps and SRE engineers', 'Platform teams'],
    summary: 'A community meetup in {city} for DevOps, SRE and platform engineers.',
    expect: ['Three practitioner talks and open discussion.'],
    sessions: ['Talk: incident reviews that help', 'Talk: internal developer platforms', 'Talk: observability on a budget', 'Networking'],
  },
  {
    key: 'cyber',
    names: ['Cyber Resilience Summit', 'Zero Trust Forum', 'CISO Leadership Roundtable'],
    eventType: 'summit',
    format: 'conference',
    categoryIds: ['cybersecurity'],
    technologyIds: ['azure', 'aws'],
    industryIds: ['bfsi', 'it', 'government', 'healthcare'],
    tags: ['Cybersecurity', 'Zero Trust', 'CISO', 'Compliance'],
    days: [1, 2],
    cities: ['delhi', 'gurugram', 'noida', 'mumbai', 'bengaluru', 'hyderabad'],
    organizerIds: ['org-securenext'],
    audience: ['CISOs and security heads', 'Risk and compliance leaders', 'Security architects'],
    summary: 'A {days} summit in {city} on security leadership, zero trust and regulatory compliance.',
    expect: ['Talks on ransomware readiness and incident response.', 'Panels on data protection compliance.', 'Closed-door CISO roundtables.'],
    sessions: [...conferenceSessions('cybersecurity'), 'Data protection compliance: what changes'],
  },
  {
    key: 'supply-chain',
    names: ['Supply Chain Excellence Summit', 'Procurement Leaders Forum'],
    eventType: 'summit',
    format: 'conference',
    categoryIds: ['supply-chain', 'procurement', 'logistics'],
    technologyIds: ['sap', 'erp-generic', 'ml'],
    industryIds: ['manufacturing', 'retail', 'logistics', 'pharma'],
    tags: ['Supply Chain', 'Procurement', 'Planning', 'Logistics'],
    days: [1, 2],
    cities: ['mumbai', 'delhi', 'bengaluru', 'chennai', 'ahmedabad', 'kolkata'],
    organizerIds: ['org-scl-network'],
    audience: ['Supply chain and procurement heads', 'Planning teams', 'Logistics leaders'],
    summary: 'A {days} summit in {city} on supply chain planning, procurement and logistics technology.',
    expect: ['Case studies on demand planning and supplier risk.', 'Sessions on procurement automation.'],
    sessions: conferenceSessions('supply chain'),
  },
  {
    key: 'logistics-expo',
    names: ['Logistics & Warehousing Expo', 'Cold Chain Expo'],
    eventType: 'expo',
    format: 'expo',
    categoryIds: ['logistics', 'supply-chain'],
    technologyIds: ['iot', 'robotics'],
    industryIds: ['logistics', 'retail', 'pharma'],
    tags: ['Logistics', 'Warehousing', 'Exhibition'],
    days: [3, 3],
    cities: ['mumbai', 'delhi', 'chennai', 'navi-mumbai', 'bengaluru'],
    organizerIds: ['org-kaveri-media', 'org-indotrade'],
    audience: ['Warehouse and logistics managers', 'Supply chain buyers'],
    summary: 'A {days} exhibition in {city} for logistics, warehousing and material handling.',
    expect: ['Exhibitors across warehouse automation, racking and fleet technology.', 'Live demos of material-handling equipment.'],
    sessions: ['Inauguration', 'Seminar: warehouse automation', 'Seminar: cold chain', 'Networking'],
  },
  {
    key: 'cfo-forum',
    names: ['CFO Technology Forum', 'Finance Transformation Summit'],
    eventType: 'business_forum',
    format: 'conference',
    categoryIds: ['finance-tech', 'erp'],
    technologyIds: ['sap', 'oracle', 'erp-generic', 'rpa'],
    industryIds: ['bfsi', 'manufacturing', 'retail'],
    tags: ['Finance', 'CFO', 'ERP', 'Automation'],
    days: [1, 1],
    cities: ['mumbai', 'delhi', 'bengaluru', 'chennai'],
    organizerIds: ['org-finlead'],
    audience: ['CFOs and controllers', 'Finance transformation teams'],
    summary: 'A one-day forum in {city} for finance leaders on ERP, close automation and reporting.',
    expect: ['Case studies on faster close and automated reconciliation.', 'Panels on finance ERP choices.'],
    sessions: conferenceSessions('finance technology'),
  },
  {
    key: 'fintech',
    names: ['FinTech Conclave', 'Digital Payments Summit'],
    eventType: 'conference',
    format: 'conference',
    categoryIds: ['fintech'],
    technologyIds: ['blockchain', 'genai'],
    industryIds: ['bfsi'],
    tags: ['FinTech', 'Payments', 'Banking'],
    days: [1, 2],
    cities: ['mumbai', 'bengaluru', 'gurugram', 'gandhinagar'],
    organizerIds: ['org-finlead', 'org-summit-works'],
    audience: ['Banking and fintech leaders', 'Product and risk teams'],
    summary: 'A {days} conference in {city} on payments, lending technology and digital banking.',
    expect: ['Talks on payments infrastructure and lending.', 'Startup showcase.'],
    sessions: conferenceSessions('fintech'),
  },
  {
    key: 'cio-summit',
    names: ['CIO Leadership Conclave', 'Digital Transformation Summit'],
    eventType: 'summit',
    format: 'conference',
    categoryIds: ['digital-transformation', 'it-services', 'erp'],
    technologyIds: ['genai', 'sap', 'azure', 'erp-generic'],
    industryIds: ['it', 'manufacturing', 'bfsi', 'retail'],
    tags: ['CIO', 'Digital Transformation', 'Leadership'],
    days: [1, 2],
    cities: ['goa', 'delhi', 'mumbai', 'bengaluru', 'hyderabad', 'jaipur'],
    organizerIds: ['org-summit-works', 'org-enterprise-pulse'],
    audience: ['CIOs and CTOs', 'Digital transformation heads'],
    summary: 'A {days} leadership summit in {city} for CIOs on transformation priorities, ERP and AI.',
    expect: ['Keynotes from technology leaders.', 'Closed-door roundtables.', 'Evening networking.'],
    sessions: [...conferenceSessions('digital transformation'), 'Roundtable: AI budgets for 2027'],
  },
  {
    key: 'startup',
    names: ['Startup Founders Meet', 'B2B SaaS Founders Day'],
    eventType: 'networking',
    format: 'meetup',
    categoryIds: ['startups', 'business'],
    technologyIds: ['genai'],
    industryIds: ['it'],
    tags: ['Startups', 'SaaS', 'Networking'],
    days: [1, 1],
    cities: ['bengaluru', 'delhi', 'mumbai', 'hyderabad', 'pune', 'chandigarh'],
    organizerIds: ['org-startup-bridge'],
    audience: ['Founders', 'Early-stage investors', 'Startup operators'],
    summary: 'An evening networking event in {city} for B2B founders and investors.',
    expect: ['Short founder talks.', 'Structured networking.'],
    sessions: ['Founder talks', 'Investor panel', 'Networking'],
  },
  {
    key: 'govtech',
    names: ['GovTech India Forum', 'e-Governance Summit'],
    eventType: 'government_event',
    format: 'conference',
    categoryIds: ['gov-tech', 'digital-transformation'],
    technologyIds: ['azure', 'genai'],
    industryIds: ['government'],
    tags: ['GovTech', 'Public Sector', 'e-Governance'],
    days: [1, 2],
    cities: ['delhi', 'lucknow', 'bhubaneswar', 'thiruvananthapuram', 'gandhinagar'],
    organizerIds: ['org-summit-works'],
    audience: ['Government technology officers', 'System integrators'],
    summary: 'A {days} forum in {city} on public-sector technology and digital services.',
    expect: ['Talks on citizen services platforms.', 'Panels with system integrators.'],
    sessions: conferenceSessions('government technology'),
  },
  {
    key: 'webinar',
    names: ['ERP Selection Webinar', 'S/4HANA Readiness Webinar', 'Odoo Upgrade Webinar'],
    eventType: 'webinar',
    format: 'webinar',
    categoryIds: ['erp'],
    technologyIds: ['erp-generic', 'sap', 'odoo'],
    industryIds: ['manufacturing', 'retail'],
    tags: ['Webinar', 'ERP', 'Online'],
    days: [1, 1],
    cities: ['bengaluru', 'hyderabad', 'pune'],
    organizerIds: ['org-enterprise-pulse', 'org-open-erp'],
    audience: ['ERP owners', 'IT managers'],
    summary: 'A one-hour online session on ERP planning and readiness.',
    expect: ['A short presentation followed by live Q&A.'],
    sessions: ['Presentation', 'Live Q&A'],
  },
];
